# Generated by Django 4.2.5 on 2023-11-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantri', '0002_alter_fruit_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravatar',
            name='fb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useravatar',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useravatar',
            name='zalo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='Quantity',
            field=models.IntegerField(verbose_name='diện tích (m2)'),
        ),
    ]
