# Generated by Django 4.2.5 on 2023-12-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantri', '0003_useravatar_fb_useravatar_phone_useravatar_zalo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('Video_id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề')),
                ('Title_phu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề phu')),
                ('VideoFile', models.FileField(upload_to='videos/')),
                ('PostingDate', models.DateField(auto_now_add=True, verbose_name='Ngày đăng')),
            ],
            options={
                'verbose_name_plural': 'video',
            },
        ),
    ]
