# Generated by Django 4.2.5 on 2023-12-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantri', '0004_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careschedule',
            name='care_date',
            field=models.TextField(verbose_name='Thời gian'),
        ),
    ]
