# Generated by Django 4.2.5 on 2023-12-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantri', '0005_alter_careschedule_care_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantingplan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='plantingplan',
            name='start_date',
        ),
    ]
