# Generated by Django 4.2.5 on 2023-12-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantri', '0006_remove_plantingplan_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name_plural': 'Video trái cây'},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name_plural': 'video bài viết'},
        ),
        migrations.AlterField(
            model_name='videos',
            name='Title_phu',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề phu'),
        ),
    ]
