# Generated by Django 5.0 on 2023-12-22 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantri', '0007_alter_video_options_alter_videos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useravatar',
            options={'verbose_name_plural': 'Thông tin chi tiết User'},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='is_notification',
        ),
        migrations.AlterField(
            model_name='article',
            name='FruitID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='quantri.fruit', verbose_name='Thuộc trái cây'),
        ),
        migrations.AlterField(
            model_name='article',
            name='PostingDate',
            field=models.DateField(auto_now_add=True, verbose_name='ngày đăng'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='ResponseDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng'),
        ),
        migrations.AlterField(
            model_name='location',
            name='Name',
            field=models.CharField(max_length=255, verbose_name='Tên địa điểm '),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='Title_phu',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Nội dung'),
        ),
    ]
